In [3]:
# ANÁLISE DE VENDAS POR PRODUTO

# Importa a biblioteca 
import pandas as pd
from IPython.display import display


# Carrega o dataset limpo a partir do arquivo CSV
df = pd.read_csv("data_clean.csv")

# Exibe as primeiras linhas para conferência
display(df.head())


# CRIA A COLUNA TOTAL_VENDA

# Calcula o total da venda multiplicando
# a quantidade pelo preço unitário
df["Total_Venda"] = (df["Quantidade"] * df["Preço"]).round(2)

# Exibe o dataframe com a nova coluna
print("\nDataFrame com a coluna Total_Venda:")
display(df.head())


# CALCULA O TOTAL DE VENDAS POR PRODUTO

# Agrupa os dados por Produto
# e soma o valor total das vendas
vendas_por_produto = (
    df.groupby("Produto")["Total_Venda"]
    .sum()
    .round(2)
    .reset_index()
)

# Exibe o total de vendas por produto
print("\nTotal de vendas por produto:")
display(vendas_por_produto)


# IDENTIFICA O PRODUTO COM MAIOR VALOR DE VENDAS TOTAIS

# Ordena os produtos pelo total de vendas
# em ordem decrescente
vendas_ordenadas = vendas_por_produto.sort_values(
    by="Total_Venda",
    ascending=False
)

# Seleciona o produto com maior valor de vendas
produto_mais_vendido = vendas_ordenadas.iloc[0]

# Exibe o resultado
print("\nProduto com maior valor total de vendas:")
display(produto_mais_vendido.to_frame().T)

,ID,Data,Produto,Categoria,Quantidade,Preço
0,1,2023-01-01 00:00:00.000000000,Monitor,Informática,4,1200.0
1,2,2023-01-08 10:17:08.571428571,Impressora,Informática,4,950.0
2,3,2023-01-15 20:34:17.142857142,Teclado,Acessórios,4,250.0
3,4,2023-01-23 06:51:25.714285714,Impressora,Informática,5,950.0
4,5,2023-01-30 17:08:34.285714285,Impressora,Informática,3,950.0

DataFrame com a coluna Total_Venda:

,ID,Data,Produto,Categoria,Quantidade,Preço,Total_Venda
0,1,2023-01-01 00:00:00.000000000,Monitor,Informática,4,1200.0,4800.0
1,2,2023-01-08 10:17:08.571428571,Impressora,Informática,4,950.0,3800.0
2,3,2023-01-15 20:34:17.142857142,Teclado,Acessórios,4,250.0,1000.0
3,4,2023-01-23 06:51:25.714285714,Impressora,Informática,5,950.0,4750.0
4,5,2023-01-30 17:08:34.285714285,Impressora,Informática,3,950.0,2850.0

Total de vendas por produto:

      Produto  Total_Venda
0  Impressora      34200.0
1     Monitor      49200.0
2       Mouse       4200.0
3    Notebook     121500.0
4     Teclado      10000.0

Produto com maior valor total de vendas:

    Produto Total_Venda
3  Notebook    121500.0